### ISSUE TITLE
choose license type

### ISSUE THREAD

**Issue by donhuvy** [rikkeisoft/deployer-cakephp2#2]
I think use BSD 3-clasue license is better for enterprise. https://github.com/rikkeisoft/deployer-cakephp2#license 

With BSD license, we can close source latter if we want and ready for any commercial projects, like MacOS (by Apple Inc.) or Zend Framework (by Zend).

**Comment by hnq90** [comment]
@donhuvy 
Em nghĩ để [MIT](http://choosealicense.com/licenses/mit/) là hợp lý rồi, project này không cần license phức tạp đến thế đâu anh ạ. Có thể những dự án sau nếu cần thiết thì mình sẽ để cái đó.

**Comment by donhuvy** [comment]
Okie :) closes #2
